name: Pull Requests


on:
  workflow_dispatch:
  pull_request:
  merge_group:
  push:
    branches:
      - "renovate/**"


concurrency:
  group: "Pull Requests: ${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true


jobs:

  gradle-check:
    uses: ./.github/workflows/run_gradle_task.yml
    with:
      runs-on: ubuntu-latest
      gradle-task: >-
        check --stacktrace
      checkout-ref: ${{ inputs.checkout-ref }}
